language: python
python:
- "3.4"
- "3.5"
- "3.6"
- "3.7"
- "3.8"
- "3.9"
install:
- pip install -r requirements.txt -r test_requirements.txt
script:
- rm -rf test-reports
- pytest --pylint --junitxml=test-reports/test-results.xml
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password: something
  skip_cleanup: true
  on:
    tags: true