version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    - package:
        # Need this to force CircleCI to build on tags since they are ignored by default
        filters:
          tags:
            only: /.*/
          # Branches are automatically included
    - pypi:
        requires:
        - package
        filters:
          tags:
            only: /.*/
          # Only publish to pypi on tags, so ignore branches
          branches:
            ignore: /.*/

jobs:
  package:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pkg-manager: pip
        pip-dependency-file: test_requirements.txt
    - run:
        name: Clear out test reports
        command: rm -rf test-reports
    - run:
        name: Run tests
        command: pytest --pylint --junitxml=test-reports/test-results.xml
  pypi:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload -u "__token__" dist/*