version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    # Define a job for each python version
    - package:
        matrix:
          parameters:
            python_version: ["3.6.14", "3.7.11", "3.8.11"]
        # Need this to force CircleCI to build on tags since they are ignored by default
        filters:
          tags:
            only: /.*/
          # Branches are automatically included
    # Only runs on branches, not on tags
    - pypi-test:
        python_version: "3.7.11"
        requires:
        - package
    # Only runs on tags, not on branches
    - pypi:
        python_version: "3.7.11"
        requires:
        - package
        filters:
          tags:
            only: /.*/
          # Only publish to pypi on tags, so ignore branches
          branches:
            ignore: /.*/

jobs:
  package:
    parameters:
      python_version:
        type: string
    docker:
    - image: cimg/python:<< parameters.python_version >>
    steps:
    - checkout
    - run: pyenv versions
    - run:
        name: Override .python-version
        command: echo "<< parameters.python_version >>" > .python-version
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pkg-manager: pip
        pip-dependency-file: test_requirements.txt
    - run:
        name: Run tests
        command: pytest --pylint --junitxml=test-reports/test-results.xml
    - store_test_results:
        path: test-reports
  pypi-test:
    parameters:
      python_version:
        type: string
    docker:
    - image: cimg/python:<< parameters.python_version >>
    steps:
    - checkout
    - run:
        name: Override .python-version
        command: echo "<< parameters.python_version >>" > .python-version
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Verify dist with twine
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
  pypi:
    parameters:
      python_version:
        type: string
    docker:
    - image: cimg/python:<< parameters.python_version >>
    steps:
    - checkout
    - run:
        name: Override .python-version
        command: echo "<< parameters.python_version >>" > .python-version
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
          twine upload -u "__token__" dist/*
