version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    # Define a job for each python version
    - package36:
        python_version: 3.6.14
        # Need this to force CircleCI to build on tags since they are ignored by default
        filters:
          tags:
            only: /.*/
          # Branches are automatically included
    - package37:
        python_version: 3.7.11
        filters:
          tags:
            only: /.*/
    - package38:
        python_version: 3.8.11
        filters:
          tags:
            only: /.*/
    # Only runs on branches, not on tags
    - pypi-test:
        requires:
        - package36
        - package37
        - package38
    # Only runs on tags, not on branches
    - pypi:
        requires:
        - package36
        - package37
        - package38
        filters:
          tags:
            only: /.*/
          # Only publish to pypi on tags, so ignore branches
          branches:
            ignore: /.*/

jobs:
  package:
    parameters:
      python_version:
        type: string
    docker:
    - image: cimg/python:<< parameters.python_version >>
    steps:
    - checkout
    - run: pyenv versions
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pkg-manager: pip
        pip-dependency-file: test_requirements.txt
    - run:
        name: Run tests
        command: pytest --pylint --junitxml=test-reports/test-results.xml
    - store_test_results:
        path: test-reports
  pypi-test:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Verify dist with twine
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
  pypi:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
          twine upload -u "__token__" dist/*
